version: '3.8'

services:
   db:
      image: mysql:latest
      container_name: mysql-db
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: 123123

   phpmyadmin:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db

   uniqr.dev:
      build: .
      ports:
         - "1453:1453"
      depends_on:
         - db
